// All visible copy, in English and Arabic. Keep both languages in sync when editing.

const en = {
  meta: {
    title: 'Visa Linkk Lebanon · Visa & Travel Guidance',
  },
  skip: 'Skip to content',
  nav: {
    home: 'Home',
    services: 'Our Services',
    about: 'About Us',
    contact: 'Contact Us',
    whatsapp: 'WhatsApp',
    menu: 'Menu',
    close: 'Close menu',
    langLabel: 'Language',
  },
  hero: {
    brand: 'Visa Linkk Lebanon',
    title: ['Your next step', 'starts with', 'clear guidance.'],
    question: 'How can we help you?',
    body: 'Whether you’re planning a visit abroad, joining your partner, or exploring Australian work and training pathways, our team helps you understand the process and prepare for your next step.',
    primary: 'Explore Our Visa Services',
    secondary: 'Contact Us',
    imageAlt: 'Pigeon Rocks at Raouché, off the Beirut coast, at sunset',
    caption: 'Raouché · Beirut',
    lockup: 'Lebanon',
  },
  destinations: ['Australia', 'Italy', 'Greece', 'Spain', 'Switzerland', 'Germany', 'Portugal', 'Croatia', 'United Kingdom'],
  services: {
    title: 'Support for your visa journey',
    intro: 'From your first enquiry to preparing your documents, we help you understand what is required and coordinate the support your case needs.',
    ask: 'Ask about this',
    viewAll: 'View All Our Services',
    items: [
      {
        id: 'australia',
        label: 'Sydney',
        title: 'Australian Visa Services',
        body: 'Explore assistance with visitor, partner, employer-sponsored work, and training visa enquiries.',
        image: '/images/svc-australia',
        alt: 'Sydney Opera House and Harbour Bridge',
        message: 'Hello Visa Linkk, I’d like to ask about Australian visa services.',
      },
      {
        id: 'worldwide',
        label: 'Paris',
        title: 'Worldwide Tourist Visa Assistance',
        body: 'Get help understanding the application process and preparing documents for your chosen destination.',
        image: '/images/svc-europe',
        alt: 'The Eiffel Tower in Paris',
        message: 'Hello Visa Linkk, I’d like to ask about tourist visa assistance.',
      },
      {
        id: 'appeals',
        label: 'Next steps',
        title: 'Refusals & Appeals',
        body: 'Arrange a professional consultation to review your circumstances and discuss possible next steps.',
        image: '/images/svc-appeals',
        alt: 'Two people reviewing application documents at a table',
        message: 'Hello Visa Linkk, I’d like to arrange a consultation about a visa refusal or appeal.',
      },
      {
        id: 'documents',
        label: 'Your file',
        title: 'Document Preparation & Translation',
        body: 'Get support with translations, invitation letters, supporting documents, and organising your file.',
        image: '/images/svc-documents',
        alt: 'An open passport filled with entry stamps',
        message: 'Hello Visa Linkk, I’d like to ask about document preparation and translation.',
      },
    ],
  },
  sheet: {
    title: 'All our services',
    close: 'Close',
    ask: 'Ask on WhatsApp',
    groups: [
      {
        id: 'australia',
        title: 'Australian Visa Services',
        items: ['Visitor visa enquiries', 'Partner visa enquiries', 'Employer-sponsored work visa enquiries', 'Training visa enquiries'],
      },
      {
        id: 'worldwide',
        title: 'Worldwide Tourist Visa Assistance',
        items: ['Understanding the application process', 'Preparing documents for your chosen destination', 'Schengen visas for travel in Europe'],
      },
      {
        id: 'appeals',
        title: 'Refusals & Appeals',
        items: ['A professional consultation to review your circumstances', 'Discussing possible next steps'],
      },
      {
        id: 'documents',
        title: 'Document Preparation & Translation',
        items: ['Translations', 'Invitation letters', 'Supporting documents', 'Organising your file'],
      },
    ],
  },
  why: {
    title: 'Why choose VisaLinkk?',
    items: [
      'Personal attention to your circumstances',
      'Communication in Arabic and English',
      'Clear explanations of the process and fees',
      'Practical document preparation support',
      'Coordination with qualified professionals where required',
    ],
    imageAlt: 'The view from an aeroplane window above the clouds',
  },
  how: {
    title: 'How it works',
    steps: [
      { title: 'Tell us what you need', body: 'Explore our services or contact our team with your enquiry.' },
      { title: 'Understand your options', body: 'We explain the next steps and help identify the appropriate assistance or consultation.' },
      { title: 'Prepare your documents', body: 'Our team helps you organise your file and coordinate the next stage.' },
    ],
    stepLabel: 'Step',
  },
  next: {
    title: 'Ready to take the next step?',
    body: 'Tell us about your plans. Let’s discuss how we can help.',
    primary: 'Chat with Us on WhatsApp',
    secondary: 'Book a Consultation',
    map: 'Find Our Office',
  },
  messages: {
    general: 'Hello Visa Linkk, I’d like to ask about your services.',
    consultation: 'Hello Visa Linkk, I’d like to book a consultation.',
  },
  footer: {
    name: 'VisaLinkk Lebanon',
    office: 'Office',
    contact: 'Contact',
    hours: 'Hours',
    explore: 'Explore',
    disclaimer: 'Visa decisions are made by the relevant government authorities. Assistance or consultation does not guarantee approval.',
    rights: 'All rights reserved.',
  },
  floating: 'Chat on WhatsApp',
  newTab: '(opens WhatsApp)',
  mapNewTab: '(opens Google Maps)',
}

const ar = {
  meta: {
    title: 'فيزا لينك لبنان · إرشاد في التأشيرات والسفر',
  },
  skip: 'انتقل إلى المحتوى',
  nav: {
    home: 'الرئيسية',
    services: 'خدماتنا',
    about: 'من نحن',
    contact: 'تواصل معنا',
    whatsapp: 'واتساب',
    menu: 'القائمة',
    close: 'إغلاق القائمة',
    langLabel: 'اللغة',
  },
  hero: {
    brand: 'فيزا لينك لبنان',
    title: ['خطوتك التالية', 'تبدأ بتوجيهٍ', 'واضح.'],
    question: 'كيف يمكننا مساعدتك؟',
    body: 'سواء كنت تخطط لزيارة في الخارج، أو للالتحاق بشريك حياتك، أو تستكشف مسارات العمل والتدريب في أستراليا، يساعدك فريقنا على فهم الإجراءات والاستعداد لخطوتك التالية.',
    primary: 'اكتشف خدمات التأشيرات',
    secondary: 'تواصل معنا',
    imageAlt: 'صخرة الروشة قبالة شاطئ بيروت عند الغروب',
    caption: 'الروشة · بيروت',
    lockup: 'لبنان',
  },
  destinations: ['أستراليا', 'إيطاليا', 'اليونان', 'إسبانيا', 'سويسرا', 'ألمانيا', 'البرتغال', 'كرواتيا', 'المملكة المتحدة'],
  services: {
    title: 'نرافقك في رحلة التأشيرة',
    intro: 'من استفسارك الأول وحتى تجهيز مستنداتك، نساعدك على فهم المطلوب وننسّق الدعم الذي يحتاجه ملفك.',
    ask: 'استفسر عن هذه الخدمة',
    viewAll: 'عرض جميع خدماتنا',
    items: [
      {
        id: 'australia',
        label: 'سيدني',
        title: 'خدمات التأشيرات الأسترالية',
        body: 'مساعدة في الاستفسارات المتعلقة بتأشيرات الزيارة والشريك والعمل بكفالة صاحب العمل والتدريب.',
        image: '/images/svc-australia',
        alt: 'دار الأوبرا وجسر الميناء في سيدني',
        message: 'مرحباً فيزا لينك، أود الاستفسار عن خدمات التأشيرات الأسترالية.',
      },
      {
        id: 'worldwide',
        label: 'باريس',
        title: 'المساعدة في التأشيرات السياحية حول العالم',
        body: 'مساعدة في فهم إجراءات التقديم وتجهيز المستندات للوجهة التي تختارها.',
        image: '/images/svc-europe',
        alt: 'برج إيفل في باريس',
        message: 'مرحباً فيزا لينك، أود الاستفسار عن المساعدة في التأشيرات السياحية.',
      },
      {
        id: 'appeals',
        label: 'الخطوات التالية',
        title: 'حالات الرفض والاستئناف',
        body: 'احجز استشارة مهنية لمراجعة وضعك ومناقشة الخطوات الممكنة.',
        image: '/images/svc-appeals',
        alt: 'شخصان يراجعان مستندات طلب على طاولة',
        message: 'مرحباً فيزا لينك، أود ترتيب استشارة بخصوص رفض تأشيرة أو استئناف.',
      },
      {
        id: 'documents',
        label: 'ملفك',
        title: 'تجهيز المستندات والترجمة',
        body: 'دعم في الترجمات ورسائل الدعوة والمستندات الداعمة وتنظيم ملفك.',
        image: '/images/svc-documents',
        alt: 'جواز سفر مفتوح مليء بأختام الدخول',
        message: 'مرحباً فيزا لينك، أود الاستفسار عن تجهيز المستندات والترجمة.',
      },
    ],
  },
  sheet: {
    title: 'جميع خدماتنا',
    close: 'إغلاق',
    ask: 'استفسر عبر واتساب',
    groups: [
      {
        id: 'australia',
        title: 'خدمات التأشيرات الأسترالية',
        items: ['الاستفسار عن تأشيرات الزيارة', 'الاستفسار عن تأشيرات الشريك', 'الاستفسار عن تأشيرات العمل بكفالة صاحب العمل', 'الاستفسار عن تأشيرات التدريب'],
      },
      {
        id: 'worldwide',
        title: 'المساعدة في التأشيرات السياحية حول العالم',
        items: ['فهم إجراءات التقديم', 'تجهيز المستندات للوجهة التي تختارها', 'تأشيرات شنغن للسفر إلى أوروبا'],
      },
      {
        id: 'appeals',
        title: 'حالات الرفض والاستئناف',
        items: ['استشارة مهنية لمراجعة وضعك', 'مناقشة الخطوات الممكنة'],
      },
      {
        id: 'documents',
        title: 'تجهيز المستندات والترجمة',
        items: ['الترجمات', 'رسائل الدعوة', 'المستندات الداعمة', 'تنظيم ملفك'],
      },
    ],
  },
  why: {
    title: 'لماذا فيزا لينك؟',
    items: [
      'اهتمام شخصي بظروفك',
      'تواصل بالعربية والإنجليزية',
      'شرح واضح للإجراءات والرسوم',
      'دعم عملي في تجهيز المستندات',
      'تنسيق مع مختصين مؤهلين عند الحاجة',
    ],
    imageAlt: 'منظر من نافذة طائرة فوق الغيوم',
  },
  how: {
    title: 'كيف نعمل',
    steps: [
      { title: 'أخبرنا بما تحتاجه', body: 'تصفّح خدماتنا أو تواصل مع فريقنا باستفسارك.' },
      { title: 'افهم خياراتك', body: 'نشرح لك الخطوات التالية ونساعدك على تحديد المساعدة أو الاستشارة المناسبة.' },
      { title: 'جهّز مستنداتك', body: 'يساعدك فريقنا على تنظيم ملفك وتنسيق المرحلة التالية.' },
    ],
    stepLabel: 'الخطوة',
  },
  next: {
    title: 'مستعد للخطوة التالية؟',
    body: 'أخبرنا عن خططك، ولنتحدث عن كيف يمكننا مساعدتك.',
    primary: 'تحدث معنا عبر واتساب',
    secondary: 'احجز استشارة',
    map: 'موقع مكتبنا',
  },
  messages: {
    general: 'مرحباً فيزا لينك، أود الاستفسار عن خدماتكم.',
    consultation: 'مرحباً فيزا لينك، أود حجز استشارة.',
  },
  footer: {
    name: 'فيزا لينك لبنان',
    office: 'المكتب',
    contact: 'التواصل',
    hours: 'ساعات العمل',
    explore: 'تصفّح',
    disclaimer: 'تصدر قرارات التأشيرات عن الجهات الحكومية المختصة، ولا تضمن المساعدة أو الاستشارة الحصول على الموافقة.',
    rights: 'جميع الحقوق محفوظة.',
  },
  floating: 'تحدث معنا عبر واتساب',
  newTab: '(يفتح واتساب)',
  mapNewTab: '(يفتح خرائط Google)',
}

export const content = { en, ar }
